# Generated by Django 5.2.4 on 2025-07-12 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Donor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('national_id', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('city', models.CharField(max_length=100)),
                ('last_donation_date', models.DateField(blank=True, null=True)),
                ('can_donate', models.BooleanField(default=True)),
                ('registration_date', models.DateField(auto_now_add=True)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('total_donations', models.IntegerField(default=0)),
                ('blood_type', models.CharField(blank=True, max_length=4, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
