# Generated by Django 5.2.4 on 2025-07-10 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Donor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('city', models.CharField(max_length=100)),
                ('last_donation_date', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
