# Generated by Django 5.2.4 on 2025-07-12 03:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donor',
            name='blood_type',
        ),
    ]
