# Generated by Django 5.2 on 2025-07-19 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='donor',
            name='blood_type',
            field=models.CharField(blank=True, help_text='Blood type is set after first donation and cannot be changed', max_length=3, null=True),
        ),
    ]
