# Generated by Django 5.2.4 on 2025-07-16 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('donor', 'Donor'), ('hospital', 'Hospital'), ('bank_employee', 'Blood Bank')], max_length=20),
        ),
    ]
