# Generated by Django 5.2.4 on 2025-07-13 00:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bloodbank', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('donation_date', models.DateField(auto_now_add=True, verbose_name='Donation Date')),
                ('virus_test_result', models.BooleanField(default=False, help_text='True = Negative (Safe), False = Positive (Unsafe)')),
                ('blood_type', models.CharField(choices=[('A+', 'A Positive'), ('A-', 'A Negative'), ('B+', 'B Positive'), ('B-', 'B Negative'), ('AB+', 'AB Positive'), ('AB-', 'AB Negative'), ('O+', 'O Positive'), ('O-', 'O Negative')], max_length=3)),
                ('quantity_ml', models.IntegerField(default=450)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('rejected_virus', 'Rejected (Virus Positive)'), ('rejected_time', 'Rejected (Too Soon)'), ('accepted', 'Accepted')], default='pending', max_length=20)),
                ('expiration_date', models.DateField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('bank', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='donations', to='bloodbank.bloodbank')),
            ],
        ),
    ]
