# Generated by Django 5.2.4 on 2025-07-15 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='quantity_ml',
            field=models.IntegerField(default=1),
        ),
    ]
