# Generated by Django 5.2 on 2025-07-19 19:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloodbank', '0004_alter_bloodbank_city_delete_city'),
        ('bloodrequests', '0003_remove_bloodrequests_city'),
        ('bloodstock', '0003_alter_stock_status'),
        ('donation', '0002_initial'),
        ('notification', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemAlert',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('alert_type', models.CharField(choices=[('power_outage', 'Power Outage'), ('temperature_alert', 'Temperature Alert'), ('storage_failure', 'Storage Failure'), ('equipment_failure', 'Equipment Failure')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='high', max_length=10)),
                ('is_resolved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='notification',
            name='donor',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='sent_at',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='status',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='via_email',
        ),
        migrations.AddField(
            model_name='notification',
            name='blood_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='bloodrequests.bloodrequests'),
        ),
        migrations.AddField(
            model_name='notification',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notification',
            name='is_sent_email',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('donation_accepted', 'Donation Accepted'), ('donation_rejected', 'Donation Rejected'), ('stock_expiry', 'Stock Expiry'), ('stock_spoiled', 'Stock Spoiled'), ('power_outage', 'Power Outage Alert'), ('storage_issue', 'Storage Issue'), ('blood_request', 'Blood Request'), ('system_alert', 'System Alert')], default='system_alert', max_length=20),
        ),
        migrations.AddField(
            model_name='notification',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=10),
        ),
        migrations.AddField(
            model_name='notification',
            name='read_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='stock',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='bloodstock.stock'),
        ),
        migrations.AddField(
            model_name='notification',
            name='title',
            field=models.CharField(default='unknown', max_length=200),
        ),
        migrations.AddField(
            model_name='notification',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='notification',
            name='message',
            field=models.TextField(default=''),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', 'is_read'], name='notificatio_user_id_543da6_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['notification_type'], name='notificatio_notific_a5f01d_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['priority'], name='notificatio_priorit_e623ff_idx'),
        ),
        migrations.AddField(
            model_name='systemalert',
            name='affected_stock',
            field=models.ManyToManyField(blank=True, related_name='system_alerts', to='bloodstock.stock'),
        ),
        migrations.AddField(
            model_name='systemalert',
            name='blood_bank',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='system_alerts', to='bloodbank.bloodbank'),
        ),
    ]
