# Generated by Django 5.2.4 on 2025-07-13 00:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bloodstock', '0001_initial'),
        ('donation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='donation',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock', to='donation.donation'),
        ),
    ]
