# Generated by Django 5.2.4 on 2025-07-13 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloodrequests', '0003_bloodrequests_patient'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloodrequests',
            name='blood_type',
            field=models.CharField(blank=True, choices=[('A+', 'A Positive'), ('A-', 'A Negative'), ('B+', 'B Positive'), ('B-', 'B Negative'), ('AB+', 'AB Positive'), ('AB-', 'AB Negative'), ('O+', 'O Positive'), ('O-', 'O Negative')], max_length=3, null=True),
        ),
    ]
