# Generated by Django 5.2.4 on 2025-07-16 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloodrequests', '0004_bloodrequests_blood_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloodrequests',
            name='city',
            field=models.CharField(default='cairo', max_length=100),
            preserve_default=False,
        ),
    ]
